name: Keep Streamlit App Awake

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: 

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit URL
        run: |
          curl -sL https://chromatix-color-editing-tool-7cdszq8kzfnivcauucdsgz.streamlit.app/_stcore/health > /dev/null
          echo "Streamlit app pinged successfully!"
